version: '3.8'

services:
  container_a:
    build: ./container_a
    networks:
      ctf_net:
        ipv4_address: 172.20.0.10
    volumes:
      - auth_sync:/auth_sync
    restart: unless-stopped

  container_b:
    build: ./container_b
    ports:
      - "2222:22"
    networks:
      ctf_net:
        ipv4_address: 172.20.0.11
    volumes:
      - auth_sync:/auth_sync
      - socket_vol:/tmp_sock
    restart: unless-stopped

  container_c:
    build: ./container_c
    environment:
      - FLAG=${FLAG:-flag{local_test_dynamic_flag_999}} 
    networks:
      ctf_net:
        ipv4_address: 172.20.0.12
    volumes:
      - socket_vol:/sock_data
    restart: unless-stopped

networks:
  ctf_net:
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  auth_sync:
  socket_vol:
