from http.server import BaseHTTPRequestHandler, HTTPServer
import urllib.parse
import os
import time

class RealVaultServer(BaseHTTPRequestHandler):
    def do_POST(self):
        time.sleep(0.5)
        
        length = int(self.headers.get('Content-Length', 0))
        post_data = self.rfile.read(length).decode('utf-8')
        params = urllib.parse.parse_qs(post_data)

        if self.path == '/api/vault/unlock':
            auth = params.get('auth', [''])[0]
            
            # Read the dynamic key generated by the bot on boot
            try:
                with open('/auth_sync/.vault_c_dynamic.key', 'r') as f:
                    real_key_c = f.read().strip()
            except:
                real_key_c = "error"

            if auth == real_key_c:
                flag = os.environ.get('FLAG', 'flag{local_test_dynamic_flag_999}')
                
                # The massive success banner!
                banner = f"""\033[32m
 ██████╗ ██████╗ ███╗   ██╗ ██████╗ ██████╗  █████╗ ████████╗██╗   ██╗███████╗
 ██╔════╝██╔═══██╗████╗  ██║██╔════╝ ██╔══██╗██╔══██╗╚══██╔══╝██║   ██║██╔════╝
 ██║     ██║   ██║██╔██╗ ██║██║  ███╗██████╔╝███████║   ██║   ██║   ██║███████╗
 ██║     ██║   ██║██║╚██╗██║██║   ██║██╔══██╗██╔══██║   ██║   ██║   ██║╚════██║
 ╚██████╗╚██████╔╝██║ ╚████║╚██████╔╝██║  ██║██║  ██║   ██║   ╚██████╔╝███████║
 ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚══════╝

                 VAULT UNLOCKED SUCCESSFULLY!
                 
         FLAG: {flag}
\033[0m
"""
                self.send_response(200)
                self.end_headers()
                self.wfile.write(banner.encode('utf-8'))
            else:
                self.send_response(403)
                self.end_headers()
                self.wfile.write(b"FAIL: Invalid Vault Key.\n")

HTTPServer(('127.0.0.1', 8081), RealVaultServer).serve_forever()
